name: 'Codespell with annotations'
author: 'Peter Newman'
description: 'Codespell with annotations for Pull Request'
inputs:
  builtin:
    description: 'Comma-separated list of builtin dictionaries to include'
    required: false
    default: ''
  check_filenames:
    description: 'If set, check file names as well'
    required: false
    default: ''
  check_hidden:
    description: 'If set, check hidden files (those starting with ".") as well'
    required: false
    default: ''
  exclude_file:
    description: 'File with lines that should not be checked for spelling mistakes'
    required: false
    default: ''
  ignore_words_file:
    description: 'File with a list of words to be ignored'
    required: false
    default: ''
  ignore_words_list:
    description: 'Comma-separated list of words to be ignored'
    required: false
    default: ''
  path:
    description: 'Path to run codespell in'
    required: false
    default: ''
  skip:
    description: 'Comma-separated list of files to skip (it accepts globs as well)'
    required: false
    default: './.git'
  only_warn:
    description: 'If set, only warn, never error'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
